name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]
    branches:
      - main
  schedule:
    - cron: '0 5 * * 6/2' # Run every two weeks on Saturday at 5:00 UTC

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl-version: [ "1.26", "1.27", "1.28" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   ref: main
      
      - name: Set Docker image tag
        id: set-tag
        run: |
          TAG=$(date +%y%m%d.%H%M%S)
          echo "TAG=$TAG" >> "$GITHUB_ENV"
          echo "IMAGE_REF=ghcr.io/$GITHUB_REPOSITORY-${{ matrix.kubectl-version }}:${TAG}" >> "$GITHUB_ENV"
          echo "IMAGE_LATEST=ghcr.io/$GITHUB_REPOSITORY-${{ matrix.kubectl-version }}:latest" >> "$GITHUB_ENV"
      
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_REF }} -t ${{ env.IMAGE_LATEST }} --progress=plain --build-arg KUBECTL_VERSION=${{ matrix.kubectl-version }} .

      - name: Scan Docker image with trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_REF }}'
          # format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
          format: 'sarif'
          output: 'trivy-results-image.sarif'

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-image.sarif'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ${{ env.IMAGE_REF }}
          docker push ${{ env.IMAGE_LATEST }}

